### ISSUE TITLE
Hold shift to display the tooltip in combat

### ISSUE THREAD

**Issue by spiralofhope** [Xruptor/xanTooltipHoudini#1]
Title says it all.

Sometimes it's useful to still display tooltips while in combat.

**Comment by Xruptor** [comment]
Hmm this seems totally doable.  Let me see when I get a spare chance to update it for the Shift modifier.  Though I'm not entirely sure if the combat lock down will affect it.  Once of the issues blizzard has is making UI modifications while the combat lock down is in effect.

**Comment by Xruptor** [comment]
Updated for Legion
-Updated TOC for Legion
-You can now hold down the SHIFT key during combat to view the tooltips.
