### ISSUE TITLE
Request: Being able to toggle tooltips on/off unrelated to combat

### ISSUE THREAD

**Issue by khelge** [Xruptor/xanTooltipHoudini#2]
Is it possible to make a toggle for disabling/enabling tooltips all together in the game? Togglable via /xth tooltip or something

**Comment by Xruptor** [comment]
Hmm do you just want to turn off tooltips period in game?  If so I thought there was an option for that built into the UI.  I also think there is a macro you can do that does the same thing.  Let me know if that's what you want to do.  I mean I can put an option to disable all the tooltips completely, but I'm sure there has to be something already there for that.  Right now this addon just disables the tooltips while in combat.

**Comment by Xruptor** [comment]
Haven't heard back since Sep 13.  Closing ticket,
